name: Draft Release

# This is the name of the default branch
tag: main

categories:
  - title: 🚀 New Features
    labels: feature
  - title: 🐛 Bug Fixes
    labels: bug
  - title: 🧹 Maintenance
    labels: maintenance
  - title: 📚 Documentation
    labels: documentation

change-template: '- ${title} (#${number}) @${author}'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/tawanda-kembo/code-collator/compare/$PREVIOUS_TAG...$TAG_NAME